import React from "react";
import { createContext } from "react";

const Context=createContext('')


export const Contextprovider=({children})=>{
    const time='updated 12 days ago'
    const data= [
        {
          appName: "Todo App",
          usedTechnology: ["React", "Node.js", "Firebase"],
          dataStorage: "12 KB",
          publicTime: "2024-12-22T08:00:00Z",
          appVersion: "1.0.0",
          author: "John Doe",
          description: "A simple app to manage daily routines and tasks.",
          license: "MIT",
          platform: "Web",
          activeUsers: 1200,
          visibility: "public",
        },
        {
          appName: "TaskMaster",
          usedTechnology: ["Angular", "Node.js", "MongoDB"],
          dataStorage: "20 KB",
          publicTime: "2024-12-20T10:00:00Z",
          appVersion: "2.3.1",
          author: "Jane Smith",
          description: "An app to organize and track tasks for teams.",
          license: "Apache-2.0",
          platform: "Web",
          activeUsers: 5500,
          visibility: "private",
        },
        {
          appName: "PhotoShare",
          usedTechnology: ["Vue", "Firebase"],
          dataStorage: "50 KB",
          publicTime: "2024-11-15T11:30:00Z",
          appVersion: "1.2.0",
          author: "Alice Brown",
          description: "A photo-sharing app with real-time updates.",
          license: "MIT",
          platform: "Web",
          activeUsers: 3000,
          visibility: "public",
        },
        {
          appName: "BudgetTracker",
          usedTechnology: ["React", "Node.js", "MongoDB"],
          dataStorage: "35 KB",
          publicTime: "2024-10-01T09:00:00Z",
          appVersion: "1.5.0",
          author: "Mike Johnson",
          description: "Manage your personal finances and budget.",
          license: "GPL-3.0",
          platform: "Mobile",
          activeUsers: 2200,
          visibility: "private",
        },
        {
          appName: "WorkoutPal",
          usedTechnology: ["React Native", "Firebase"],
          dataStorage: "25 KB",
          publicTime: "2024-08-12T10:45:00Z",
          appVersion: "2.0.1",
          author: "Samantha Green",
          description: "An app to track workouts and fitness goals.",
          license: "MIT",
          platform: "Mobile",
          activeUsers: 4000,
          visibility: "public",
        },
        {
          appName: "RecipeMaster",
          usedTechnology: ["React", "Node.js", "MongoDB"],
          dataStorage: "30 KB",
          publicTime: "2024-06-10T14:00:00Z",
          appVersion: "1.3.2",
          author: "Lucas White",
          description: "Find and share recipes with friends and family.",
          license: "MIT",
          platform: "Web",
          activeUsers: 1500,
          visibility: "public",
        },
        {
          appName: "NewsHub",
          usedTechnology: ["Vue", "Node.js", "Firebase"],
          dataStorage: "40 KB",
          publicTime: "2024-04-25T07:30:00Z",
          appVersion: "1.1.0",
          author: "David Black",
          description: "Get the latest news from around the world.",
          license: "GPL-3.0",
          platform: "Mobile",
          activeUsers: 5000,
          visibility: "private",
        },
        {
          appName: "TravelBuddy",
          usedTechnology: ["Angular", "Firebase"],
          dataStorage: "18 KB",
          publicTime: "2024-03-18T12:15:00Z",
          appVersion: "2.0.3",
          author: "Sophia Williams",
          description: "Plan and organize your trips with ease.",
          license: "MIT",
          platform: "Web",
          activeUsers: 2500,
          visibility: "public",
        },
        {
          appName: "E-Commerce App",
          usedTechnology: ["React", "Node.js", "Stripe"],
          dataStorage: "100 KB",
          publicTime: "2024-01-01T09:00:00Z",
          appVersion: "3.0.0",
          author: "Emma Harris",
          description: "Buy and sell products online.",
          license: "MIT",
          platform: "Web",
          activeUsers: 12000,
          visibility: "private",
        },
        {
          appName: "SmartHome App",
          usedTechnology: ["React Native", "AWS"],
          dataStorage: "15 KB",
          publicTime: "2024-05-09T13:00:00Z",
          appVersion: "1.0.0",
          author: "Jack Lee",
          description: "Control your smart home devices from anywhere.",
          license: "Apache-2.0",
          platform: "Mobile",
          activeUsers: 8000,
          visibility: "public",
        },
        {
          appName: "WeatherNow",
          usedTechnology: ["Vue", "Node.js", "OpenWeatherAPI"],
          dataStorage: "10 KB",
          publicTime: "2024-07-18T08:00:00Z",
          appVersion: "2.1.0",
          author: "Oliver Clark",
          description: "Get live weather updates from around the world.",
          license: "MIT",
          platform: "Mobile",
          activeUsers: 15000,
          visibility: "private",
        },
        {
          appName: "ToDoMaster",
          usedTechnology: ["React", "Firebase"],
          dataStorage: "8 KB",
          publicTime: "2023-12-12T10:00:00Z",
          appVersion: "1.0.1",
          author: "Isabella Scott",
          description: "Manage your daily tasks and to-do lists.",
          license: "GPL-3.0",
          platform: "Web",
          activeUsers: 2000,
          visibility: "public",
        },
        {
          appName: "TaskOrganizer",
          usedTechnology: ["Vue", "Node.js"],
          dataStorage: "22 KB",
          publicTime: "2024-02-05T11:30:00Z",
          appVersion: "3.0.1",
          author: "James Miller",
          description: "Organize your tasks and productivity.",
          license: "MIT",
          platform: "Mobile",
          activeUsers: 3500,
          visibility: "private",
        },
        {
          appName: "PhotoEditor Pro",
          usedTechnology: ["React Native", "AWS"],
          dataStorage: "70 KB",
          publicTime: "2024-05-05T14:30:00Z",
          appVersion: "2.5.0",
          author: "Michael Adams",
          description: "Advanced photo editing tool with filters and effects.",
          license: "MIT",
          platform: "Mobile",
          activeUsers: 6000,
          visibility: "public",
        },
        {
          appName: "ChatBox",
          usedTechnology: ["Angular", "Node.js", "Socket.io"],
          dataStorage: "45 KB",
          publicTime: "2024-09-09T16:00:00Z",
          appVersion: "1.0.0",
          author: "Charlotte Wilson",
          description: "A simple app for instant messaging.",
          license: "MIT",
          platform: "Web",
          activeUsers: 8000,
          visibility: "private",
        },
        {
          appName: "FitnessTracker",
          usedTechnology: ["React", "Firebase"],
          dataStorage: "60 KB",
          publicTime: "2024-03-28T09:15:00Z",
          appVersion: "2.0.1",
          author: "Liam Walker",
          description: "Track your workouts and fitness progress.",
          license: "GPL-3.0",
          platform: "Mobile",
          activeUsers: 4000,
          visibility: "public",
        },
        {
          appName: "SocialMediaApp",
          usedTechnology: ["React Native", "MongoDB"],
          dataStorage: "120 KB",
          publicTime: "2024-02-15T12:00:00Z",
          appVersion: "1.7.0",
          author: "Grace Lee",
          description: "A social media platform for sharing posts and photos.",
          license: "MIT",
          platform: "Web",
          activeUsers: 25000,
          visibility: "private",
        },
        {
          appName: "E-Learning",
          usedTechnology: ["Angular", "Node.js", "MongoDB"],
          dataStorage: "80 KB",
          publicTime: "2024-04-01T08:00:00Z",
          appVersion: "1.0.0",
          author: "Ethan Allen",
          description: "A platform for online learning and courses.",
          license: "MIT",
          platform: "Web",
          activeUsers: 10000,
          visibility: "public",
        }
      ];
      const value={data,time}


      return(
        <Context.Provider value={value} >
            {children}


        </Context.Provider>
        
      )
      
}
export default Context;